apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cklw5luwo-nodejs
  janus-idp.io/tekton: cklw5luwo-nodejs
  backstage.io/kubernetes-id: cklw5luwo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cklw5luwo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
